name: Django CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install dependecies
      run: |
        pip3 install -r requirements.txt

    - name: run django tests
      run: |
        python3 manage.py test
